Add API endpoints for
BuildForSDG/Team-226-Backend pull request #25
Opened 2020-05-22 00:18 UTC by sonegillis

## Description
1. Creating, Updating and deleting a land, post and category
2. Uploading images for land and post
3. Getting all land, and post and categories
4. Getting all land, post and categories for a particular user
5. Add post to a list
6. Delete a post from a list

Fixes #4, #5, #8, #12, #13

## How Has This Been Tested?
All the API endpoints in this PR can be seen after running the project locally and visiting _http://localhost:8000/api/doc/swagger/_ or _http://localhost:8000/api/doc/redoc/_

To run the tests for the endpoint do 
```shell
    $ poetry run pytest
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

2020-05-22 06:05 UTC, wadleo requested changes
Hey @sonegillis, can you pull from the develop branch, there are some conflicts here with the latest changes to develop, thanks. Also, when you do that, the circleci build will start passing since it fails because of the old configuration.

2020-05-22 06:06 UTC, wadleo requested changes
Also, can you remove all the .idea folder and all the files in it from the commit, also the .python-version file? 
Thanks for adding the media folder to the .gitignore, also can you remove all the files you committed from the media folder.

2020-05-22 13:55 UTC, gastonche requested changes
@sonegillis the tests are failing, any idea why?

2020-05-22 20:39 UTC, sonegillis commented
> @sonegillis the tests are failing, any idea why?

Hello @gastonche thanks for the review. The codacy review is not really a test but a review for code quality. If you look at the details most of the review checks conflicts (e.g D211 and D203 are conflicting reviews and we can disable one of them). I have also looked at some of the reviews and fixed in the latest commits

2020-05-22 20:40 UTC, sonegillis commented
> Also, can you remove all the .idea folder and all the files in it from the commit, also the .python-version file?
> Thanks for adding the media folder to the .gitignore, also can you remove all the files you committed from the media folder.

Hello @wadleo thanks for your review. I have made the changes you requested

2020-05-24 09:54 UTC, wadleo requested changes
Hey bro, I see you deleted the .gitignore file and the idea files are still here.

2020-05-27 21:44 UTC, wadleo requested changes
Removed this files

2020-05-27 21:44 UTC, wadleo commented on .python-version
> +3.7.0
@sonegillis please remove this file, thanks.

2020-05-27 21:44 UTC, wadleo commented on .python-version
> +3.7.0
Also, there are binary files still here after the .python-version file

2020-05-27 21:44 UTC, wadleo commented on zero_hunger.egg-info/PKG-INFO
> +Metadata-Version: 1.2
this file also has to be removed

2020-05-27 21:44 UTC, wadleo commented on zero_hunger.egg-info/SOURCES.txt
> +README.md
this too

2020-05-27 21:44 UTC, wadleo commented on zero_hunger.egg-info/dependency_links.txt
> +
same here

2020-05-27 21:44 UTC, wadleo commented on zero_hunger.egg-info/entry_points.txt
> +[console_scripts]
same here

2020-05-27 21:44 UTC, wadleo commented on zero_hunger.egg-info/requires.txt
> +Pillow<8.0.0,>=7.1.2
in short all the whole zero_hunger.egg-info folder should be removed

2020-05-27 21:44 UTC, wadleo commented on zero_hunger/.env
> +DEBUG=True
Hey bro, please remove this file

2020-05-29 06:49 UTC, wadleo approved these changes
Ran it locally, ran tests and LGTM

2020-05-29 08:28 UTC, gastonche approved these changes

2020-05-29 13:37 UTC, Cressence approved these changes

2020-05-29 13:57 UTC, merged